import type { INodeProperties } from 'n8n-workflow';

export const marketplaceOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['marketplace'] } },
		options: [
			{
				name: 'Search Listings',
				value: 'searchListings',
				action: 'Search marketplace listings',
				description: 'Search Facebook Marketplace items with filters. Returns 24 items per call. Use end_cursor for more.',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/search',
						qs: {
							query: '={{$parameter.additionalFields.query}}',
							category_url: '={{$parameter.additionalFields.category_url}}',
							commerce_search_sort_by: '={{$parameter.additionalFields.commerce_search_sort_by}}',
							commerce_search_and_rp_condition: '={{$parameter.additionalFields.commerce_search_and_rp_condition}}',
							filter_location_latitude: '={{$parameter.additionalFields.filter_location_latitude}}',
							filter_location_longitude: '={{$parameter.additionalFields.filter_location_longitude}}',
							filter_price_lower_bound: '={{$parameter.additionalFields.filter_price_lower_bound}}',
							filter_price_upper_bound: '={{$parameter.additionalFields.filter_price_upper_bound}}',
							filter_radius_km: '={{$parameter.additionalFields.filter_radius_km}}',
							posted_today: '={{$parameter.additionalFields.posted_today}}',
							exact_match: '={{$parameter.additionalFields.exact_match}}',
							end_cursor: '={{$parameter.additionalFields.end_cursor}}',
						},
					},
				},
			},
			{
				name: 'Get Listing Details',
				value: 'getListingDetails',
				action: 'Get marketplace listing details',
				description: 'Get detailed info about a single Marketplace listing',
				routing: {
					request: { method: 'GET', url: '/facebook/marketplace/listing', qs: { listing_id: '={{$parameter.listingId}}' } },
				},
			},
			{
				name: 'Get Seller Details',
				value: 'getSellerDetails',
				action: 'Get marketplace seller details',
				description: 'Get seller profile, ratings, reviews, and badges',
				routing: {
					request: { method: 'GET', url: '/facebook/marketplace/seller', qs: { seller_id: '={{$parameter.sellerId}}' } },
				},
			},
			{
				name: 'Get Categories',
				value: 'getCategories',
				action: 'Get marketplace categories',
				description: 'Get all Marketplace categories with seo_url and category ID values',
				routing: {
					request: { method: 'GET', url: '/facebook/marketplace/categories' },
				},
			},
			{
				name: 'Find City Coordinates',
				value: 'findCityCoordinates',
				action: 'Find city coordinates',
				description: 'Get GPS coordinates for a city to use as location filters',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/city-coordinates',
						qs: {
							city: '={{$parameter.cityName}}',
							country: '={{$parameter.additionalFields.country}}',
							exactly_one: '={{$parameter.additionalFields.exactly_one}}',
						},
					},
				},
			},
			{
				name: 'Search Vehicles',
				value: 'searchVehicles',
				action: 'Search marketplace vehicles',
				description: 'Search vehicle listings with filters. Returns 24 items per call. Use end_cursor for more.',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/vehicles',
						qs: {
							sort_by: '={{$parameter.additionalFields.sort_by}}',
							filter_location_latitude: '={{$parameter.additionalFields.filter_location_latitude}}',
							filter_location_longitude: '={{$parameter.additionalFields.filter_location_longitude}}',
							filter_price_lower_bound: '={{$parameter.additionalFields.filter_price_lower_bound}}',
							filter_price_upper_bound: '={{$parameter.additionalFields.filter_price_upper_bound}}',
							filter_radius_km: '={{$parameter.additionalFields.filter_radius_km}}',
							is_c2c_listing_only: '={{$parameter.additionalFields.is_c2c_listing_only}}',
							exact_match: '={{$parameter.additionalFields.exact_match}}',
							end_cursor: '={{$parameter.additionalFields.end_cursor}}',
						},
					},
				},
			},
			{
				name: 'Search Rentals',
				value: 'searchRentals',
				action: 'Search marketplace rentals',
				description: 'Search rental property listings with filters. Returns 24 items per call. Use end_cursor for more.',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/rentals',
						qs: {
							sort_by: '={{$parameter.additionalFields.sort_by}}',
							filter_location_latitude: '={{$parameter.additionalFields.filter_location_latitude}}',
							filter_location_longitude: '={{$parameter.additionalFields.filter_location_longitude}}',
							filter_price_lower_bound: '={{$parameter.additionalFields.filter_price_lower_bound}}',
							filter_price_upper_bound: '={{$parameter.additionalFields.filter_price_upper_bound}}',
							filter_radius_km: '={{$parameter.additionalFields.filter_radius_km}}',
							filter_bedrooms_min: '={{$parameter.additionalFields.filter_bedrooms_min}}',
							filter_bedrooms_max: '={{$parameter.additionalFields.filter_bedrooms_max}}',
							filter_bathrooms_min: '={{$parameter.additionalFields.filter_bathrooms_min}}',
							filter_bathrooms_max: '={{$parameter.additionalFields.filter_bathrooms_max}}',
							is_c2c_listing_only: '={{$parameter.additionalFields.is_c2c_listing_only}}',
							end_cursor: '={{$parameter.additionalFields.end_cursor}}',
						},
					},
				},
			},
		],
		default: 'searchListings',
	},
	// --- Listing ID ---
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 24,
		description: 'Max number of results to return. Marketplace search returns 24 items per API call by default.',
		displayOptions: { show: { operation: ['searchListings', 'searchVehicles', 'searchRentals'] } },
	},
	{
		displayName: 'Listing ID',
		name: 'listingId',
		type: 'string',
		required: true,
		description: 'The Marketplace Listing ID',
		default: '',
		displayOptions: { show: { operation: ['getListingDetails'] } },
	},
	// --- Seller ID ---
	{
		displayName: 'Seller ID',
		name: 'sellerId',
		type: 'string',
		required: true,
		description: 'The Seller ID',
		default: '',
		displayOptions: { show: { operation: ['getSellerDetails'] } },
	},
	// --- City Name ---
	{
		displayName: 'City Name',
		name: 'cityName',
		type: 'string',
		required: true,
		description: 'City name to find coordinates for',
		default: 'New York',
		displayOptions: { show: { operation: ['findCityCoordinates'] } },
	},
	// --- Additional Fields: Search Listings ---
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['searchListings'] } },
		default: {},
		options: [
			{ displayName: 'Query', name: 'query', type: 'string', default: '', description: 'Search term' },
			{ displayName: 'Category URL', name: 'category_url', type: 'string', default: '', description: 'Category URL slug' },
			{ displayName: 'Sort By', name: 'commerce_search_sort_by', type: 'options', options: [{ name: 'Best Match', value: 'BEST_MATCH' }, { name: 'Newest First', value: 'CREATION_TIME_DESCEND' }, { name: 'Price: Low to High', value: 'PRICE_ASCEND' }, { name: 'Price: High to Low', value: 'PRICE_DESCEND' }], default: 'BEST_MATCH' },
			{ displayName: 'Condition', name: 'commerce_search_and_rp_condition', type: 'options', options: [{ name: 'New', value: 'new' }, { name: 'Used - Like New', value: 'used_like_new' }, { name: 'Used - Good', value: 'used_good' }, { name: 'Used - Fair', value: 'used_fair' }], default: 'new' },
			{ displayName: 'Latitude', name: 'filter_location_latitude', type: 'string', default: '', description: 'GPS latitude coordinate' },
			{ displayName: 'Longitude', name: 'filter_location_longitude', type: 'string', default: '', description: 'GPS longitude coordinate' },
			{ displayName: 'Min Price', name: 'filter_price_lower_bound', type: 'number', default: 0, description: 'Minimum price' },
			{ displayName: 'Max Price', name: 'filter_price_upper_bound', type: 'number', default: 0, description: 'Maximum price' },
			{ displayName: 'Radius (km)', name: 'filter_radius_km', type: 'number', default: 50, description: 'Search radius in km' },
			{ displayName: 'Posted Today', name: 'posted_today', type: 'boolean', default: false, description: 'Whether to limit to items posted today' },
			{ displayName: 'Exact Match', name: 'exact_match', type: 'boolean', default: false, description: 'Whether to use exact match search' },
			{ displayName: 'End Cursor', name: 'end_cursor', type: 'string', default: '', description: 'Pagination cursor' },
		],
	},
	// --- Additional Fields: City Coordinates ---
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['findCityCoordinates'] } },
		default: {},
		options: [
			{ displayName: 'Country', name: 'country', type: 'string', default: '', description: 'Country name or code' },
			{ displayName: 'Exactly One', name: 'exactly_one', type: 'boolean', default: false, description: 'Whether to return exactly one result' },
		],
	},
	// --- Additional Fields: Vehicles ---
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['searchVehicles'] } },
		default: {},
		options: [
			{ displayName: 'Sort By', name: 'sort_by', type: 'options', options: [{ name: 'Newest First', value: 'CREATION_TIME_DESCEND' }, { name: 'Price: Low to High', value: 'PRICE_ASCEND' }, { name: 'Mileage: Low to High', value: 'VEHICLE_MILEAGE_ASCEND' }, { name: 'Year: Newest First', value: 'VEHICLE_YEAR_ASCEND' }], default: 'CREATION_TIME_DESCEND' },
			{ displayName: 'Latitude', name: 'filter_location_latitude', type: 'string', default: '' },
			{ displayName: 'Longitude', name: 'filter_location_longitude', type: 'string', default: '' },
			{ displayName: 'Min Price', name: 'filter_price_lower_bound', type: 'number', default: 0 },
			{ displayName: 'Max Price', name: 'filter_price_upper_bound', type: 'number', default: 0 },
			{ displayName: 'Radius (km)', name: 'filter_radius_km', type: 'number', default: 50 },
			{ displayName: 'Individual Sellers Only', name: 'is_c2c_listing_only', type: 'boolean', default: false },
			{ displayName: 'Exact Match', name: 'exact_match', type: 'boolean', default: false },
			{ displayName: 'End Cursor', name: 'end_cursor', type: 'string', default: '', description: 'Pagination cursor' },
		],
	},
	// --- Additional Fields: Rentals ---
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['searchRentals'] } },
		default: {},
		options: [
			{ displayName: 'Sort By', name: 'sort_by', type: 'options', options: [{ name: 'Newest First', value: 'CREATION_TIME_DESCEND' }, { name: 'Price: Low to High', value: 'PRICE_ASCEND' }, { name: 'Best Match', value: 'BEST_MATCH' }], default: 'CREATION_TIME_DESCEND' },
			{ displayName: 'Latitude', name: 'filter_location_latitude', type: 'string', default: '' },
			{ displayName: 'Longitude', name: 'filter_location_longitude', type: 'string', default: '' },
			{ displayName: 'Min Price', name: 'filter_price_lower_bound', type: 'number', default: 0 },
			{ displayName: 'Max Price', name: 'filter_price_upper_bound', type: 'number', default: 0 },
			{ displayName: 'Radius (km)', name: 'filter_radius_km', type: 'number', default: 50 },
			{ displayName: 'Min Bedrooms', name: 'filter_bedrooms_min', type: 'number', default: 0 },
			{ displayName: 'Max Bedrooms', name: 'filter_bedrooms_max', type: 'number', default: 0 },
			{ displayName: 'Min Bathrooms', name: 'filter_bathrooms_min', type: 'number', default: 0 },
			{ displayName: 'Max Bathrooms', name: 'filter_bathrooms_max', type: 'number', default: 0 },
			{ displayName: 'Individual Sellers Only', name: 'is_c2c_listing_only', type: 'boolean', default: false },
			{ displayName: 'End Cursor', name: 'end_cursor', type: 'string', default: '', description: 'Pagination cursor' },
		],
	},
];
