import type { INodeProperties } from 'n8n-workflow';

export const marketplaceOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['marketplace'] } },
		options: [
			{
				name: 'Find City Coordinates',
				value: 'findCityCoordinates',
				action: 'Find city coordinates',
				description: 'Get GPS coordinates for a city to use as location filters',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/city-coordinates',
						qs: {
							city: '={{$parameter.cityName}}',
						},
					},
				},
			},
			{
				name: 'Get Categories',
				value: 'getCategories',
				action: 'Get marketplace categories',
				description: 'Get all Marketplace categories with seo_url and category ID values',
				routing: {
					request: { method: 'GET', url: '/facebook/marketplace/categories' },
				},
			},
			{
				name: 'Get Listing Details',
				value: 'getListingDetails',
				action: 'Get marketplace listing details',
				description: 'Get detailed info about a single Marketplace listing',
				routing: {
					request: { method: 'GET', url: '/facebook/marketplace/listing', qs: { listing_id: '={{$parameter.listingId}}' } },
				},
			},
			{
				name: 'Get Seller Details',
				value: 'getSellerDetails',
				action: 'Get marketplace seller details',
				description: 'Get seller profile, ratings, reviews, and badges',
				routing: {
					request: { method: 'GET', url: '/facebook/marketplace/seller', qs: { seller_id: '={{$parameter.sellerId}}' } },
				},
			},
			{
				name: 'Search Listings',
				value: 'searchListings',
				action: 'Search marketplace listings',
				description: 'Search Facebook Marketplace items with filters. Returns 24 items per call. Use end_cursor for more.',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/search',
					},
				},
			},
			{
				name: 'Search Rentals',
				value: 'searchRentals',
				action: 'Search marketplace rentals',
				description: 'Search rental property listings with filters. Returns 24 items per call. Use end_cursor for more.',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/rentals',
					},
				},
			},
			{
				name: 'Search Vehicles',
				value: 'searchVehicles',
				action: 'Search marketplace vehicles',
				description: 'Search vehicle listings with filters. Returns 24 items per call. Use end_cursor for more.',
				routing: {
					request: {
						method: 'GET',
						url: '/facebook/marketplace/vehicles',
					},
				},
			},
		],
		default: 'searchListings',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
		displayOptions: { show: { operation: ['searchListings', 'searchVehicles', 'searchRentals'] } },
	},
	{
		displayName: 'Listing ID',
		name: 'listingId',
		type: 'string',
		required: true,
		description: 'The Marketplace Listing ID',
		default: '',
		displayOptions: { show: { operation: ['getListingDetails'] } },
	},
	{
		displayName: 'Seller ID',
		name: 'sellerId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { operation: ['getSellerDetails'] } },
	},
	{
		displayName: 'City Name',
		name: 'cityName',
		type: 'string',
		required: true,
		description: 'City name to find coordinates for',
		default: 'New York',
		displayOptions: { show: { operation: ['findCityCoordinates'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['searchListings'] } },
		default: {},
		options: [
			{ displayName: 'Category URL', name: 'category_url', type: 'string', default: '', description: 'Category URL slug', routing: { send: { type: 'query', property: 'category_url' } } },
			{ displayName: 'Condition', name: 'commerce_search_and_rp_condition', type: 'options', options: [{ name: 'New', value: 'new' }, { name: 'Used - Like New', value: 'used_like_new' }, { name: 'Used - Good', value: 'used_good' }, { name: 'Used - Fair', value: 'used_fair' }], default: 'new', routing: { send: { type: 'query', property: 'commerce_search_and_rp_condition' } } },
			{ displayName: 'End Cursor', name: 'end_cursor', type: 'string', default: '', description: 'Pagination cursor', routing: { send: { type: 'query', property: 'end_cursor' } } },
			{ displayName: 'Exact Match', name: 'exact_match', type: 'boolean', default: false, description: 'Whether to use exact match search', routing: { send: { type: 'query', property: 'exact_match' } } },
			{ displayName: 'Latitude', name: 'filter_location_latitude', type: 'string', default: '', description: 'GPS latitude coordinate', routing: { send: { type: 'query', property: 'filter_location_latitude' } } },
			{ displayName: 'Longitude', name: 'filter_location_longitude', type: 'string', default: '', description: 'GPS longitude coordinate', routing: { send: { type: 'query', property: 'filter_location_longitude' } } },
			{ displayName: 'Max Price', name: 'filter_price_upper_bound', type: 'number', default: 0, description: 'Maximum price', routing: { send: { type: 'query', property: 'filter_price_upper_bound' } } },
			{ displayName: 'Min Price', name: 'filter_price_lower_bound', type: 'number', default: 0, description: 'Minimum price', routing: { send: { type: 'query', property: 'filter_price_lower_bound' } } },
			{ displayName: 'Posted Today', name: 'posted_today', type: 'boolean', default: false, description: 'Whether to limit to items posted today', routing: { send: { type: 'query', property: 'posted_today' } } },
			{ displayName: 'Query', name: 'query', type: 'string', default: '', description: 'Search term', routing: { send: { type: 'query', property: 'query' } } },
			{ displayName: 'Radius (Km)', name: 'filter_radius_km', type: 'number', default: 50, description: 'Search radius in km', routing: { send: { type: 'query', property: 'filter_radius_km' } } },
			{ displayName: 'Sort By', name: 'commerce_search_sort_by', type: 'options', options: [{ name: 'Best Match', value: 'BEST_MATCH' }, { name: 'Newest First', value: 'CREATION_TIME_DESCEND' }, { name: 'Price: Low to High', value: 'PRICE_ASCEND' }, { name: 'Price: High to Low', value: 'PRICE_DESCEND' }], default: 'BEST_MATCH', routing: { send: { type: 'query', property: 'commerce_search_sort_by' } } },
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['findCityCoordinates'] } },
		default: {},
		options: [
			{ displayName: 'Country', name: 'country', type: 'string', default: '', description: 'Country name or code', routing: { send: { type: 'query', property: 'country' } } },
			{ displayName: 'Exactly One', name: 'exactly_one', type: 'boolean', default: false, description: 'Whether to return exactly one result', routing: { send: { type: 'query', property: 'exactly_one' } } },
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['searchVehicles'] } },
		default: {},
		options: [
			{ displayName: 'End Cursor', name: 'end_cursor', type: 'string', default: '', description: 'Pagination cursor', routing: { send: { type: 'query', property: 'end_cursor' } } },
			{ displayName: 'Exact Match', name: 'exact_match', type: 'boolean', default: false, routing: { send: { type: 'query', property: 'exact_match' } } },
			{ displayName: 'Individual Sellers Only', name: 'is_c2c_listing_only', type: 'boolean', default: false, routing: { send: { type: 'query', property: 'is_c2c_listing_only' } } },
			{ displayName: 'Latitude', name: 'filter_location_latitude', type: 'string', default: '', routing: { send: { type: 'query', property: 'filter_location_latitude' } } },
			{ displayName: 'Longitude', name: 'filter_location_longitude', type: 'string', default: '', routing: { send: { type: 'query', property: 'filter_location_longitude' } } },
			{ displayName: 'Max Price', name: 'filter_price_upper_bound', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_price_upper_bound' } } },
			{ displayName: 'Min Price', name: 'filter_price_lower_bound', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_price_lower_bound' } } },
			{ displayName: 'Radius (Km)', name: 'filter_radius_km', type: 'number', default: 50, routing: { send: { type: 'query', property: 'filter_radius_km' } } },
			{ displayName: 'Sort By', name: 'sort_by', type: 'options', options: [{ name: 'Newest First', value: 'CREATION_TIME_DESCEND' }, { name: 'Price: Low to High', value: 'PRICE_ASCEND' }, { name: 'Mileage: Low to High', value: 'VEHICLE_MILEAGE_ASCEND' }, { name: 'Year: Newest First', value: 'VEHICLE_YEAR_ASCEND' }], default: 'CREATION_TIME_DESCEND', routing: { send: { type: 'query', property: 'sort_by' } } },
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { operation: ['searchRentals'] } },
		default: {},
		options: [
			{ displayName: 'End Cursor', name: 'end_cursor', type: 'string', default: '', description: 'Pagination cursor', routing: { send: { type: 'query', property: 'end_cursor' } } },
			{ displayName: 'Individual Sellers Only', name: 'is_c2c_listing_only', type: 'boolean', default: false, routing: { send: { type: 'query', property: 'is_c2c_listing_only' } } },
			{ displayName: 'Latitude', name: 'filter_location_latitude', type: 'string', default: '', routing: { send: { type: 'query', property: 'filter_location_latitude' } } },
			{ displayName: 'Longitude', name: 'filter_location_longitude', type: 'string', default: '', routing: { send: { type: 'query', property: 'filter_location_longitude' } } },
			{ displayName: 'Max Bathrooms', name: 'filter_bathrooms_max', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_bathrooms_max' } } },
			{ displayName: 'Max Bedrooms', name: 'filter_bedrooms_max', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_bedrooms_max' } } },
			{ displayName: 'Max Price', name: 'filter_price_upper_bound', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_price_upper_bound' } } },
			{ displayName: 'Min Bathrooms', name: 'filter_bathrooms_min', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_bathrooms_min' } } },
			{ displayName: 'Min Bedrooms', name: 'filter_bedrooms_min', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_bedrooms_min' } } },
			{ displayName: 'Min Price', name: 'filter_price_lower_bound', type: 'number', default: 0, routing: { send: { type: 'query', property: 'filter_price_lower_bound' } } },
			{ displayName: 'Radius (Km)', name: 'filter_radius_km', type: 'number', default: 50, routing: { send: { type: 'query', property: 'filter_radius_km' } } },
			{ displayName: 'Sort By', name: 'sort_by', type: 'options', options: [{ name: 'Newest First', value: 'CREATION_TIME_DESCEND' }, { name: 'Price: Low to High', value: 'PRICE_ASCEND' }, { name: 'Best Match', value: 'BEST_MATCH' }], default: 'CREATION_TIME_DESCEND', routing: { send: { type: 'query', property: 'sort_by' } } },
		],
	},
];